name: amt_cgs_groupe
description: "Une application de réservation de taxi par la société AMT CGS GROUPE."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  sqflite: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite_common_ffi: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/production/
